#use it with testing_pipeline.py script

gpu_idx: 0

model: vrt

netG: # common setup for tested model 
  net_type: vrt
  arguments:
    upscale: 4
    img_size: [6,64,64]
    window_size: [6,8,8]
    depths: [8,8,8,8,8,8,8, 4,4,4,4, 4,4]
    indep_reconsts: [11,12]
    embed_dims: [120,120,120,120,120,120,120, 180,180,180,180, 180,180]
    num_heads: [6,6,6,6,6,6,6, 6,6,6,6, 6,6]
    pa_frames: 2
    deformable_groups: 12
    nonblind_denoising: false
    use_checkpoint_attn: false
    use_checkpoint_ffn: false
    no_checkpoint_attn_blocks: []
    no_checkpoint_ffn_blocks: []
    spynet_path: model_zoo/vrt/spynet_sintel_final-3d2a1287.pth   # automatical download

args:
  sigma: 0
  tile: [12, 64, 64]
  tile_overlap: [0, 20, 20]
  num_workers: 16
  save_result: True
  scale: 4
  nonblind_denoising: False
  window_size: [6, 8, 8]

metrics_config: ./options/test_metrics.yaml # config file for test metrics
collected_stats_root: ../mnt/calypso/attacks/vrt # stats are at ./root/dataset_name/versions_key.yaml
stats_path: # .xlsx file with up to date stats. If None then only computed stats is saved
save_stats_name: stats.xlsx # name of .xlsx file to save computed stats. If None then stats_path is overwrited 

versions:
  baseline:
    pretrained_netG: ../mnt/calypso/checkpoints/001_VRT_videosr_bi_REDS_6frames.pth
    metrics: # metrics which are not in stats yet
      all # if all, then all metrics from metrics_config are used

  charbonnier:
    pretrained_netG: ../mnt/calypso/checkpoints/4x_train_vrt_vimeo_000/models/50000_G.pth
    metrics: # metrics which are not in stats yet
      all 

  mdtvsfa_001: 
    pretrained_netG: ../mnt/calypso/checkpoints/4x_finetune_vrt_vimeo_mdtvsfa_000/models/75000_G.pth
    metrics: # metrics which are not in stats yet
      all

  hyperiqa_001: 
    pretrained_netG: ../mnt/calypso/checkpoints/4x_finetune_vrt_vimeo_hyperiqa_001/models/75000_G.pth
    metrics: # metrics which are not in stats yet
      all

  lpips_001: 
    pretrained_netG: ../mnt/calypso/checkpoints/4x_finetune_vrt_vimeo_lpips_001/models/75000_G.pth
    metrics: # metrics which are not in stats yet
      all

  maniqa_001: 
    pretrained_netG: ../mnt/calypso/checkpoints/4x_finetune_vrt_vimeo_maniqa_001/models/75000_G.pth
    metrics: # metrics which are not in stats yet
      all

  nima_001:
    pretrained_netG: ../mnt/calypso/checkpoints/4x_finetune_vrt_vimeo_nima_001/models/75000_G.pth
    metrics: # metrics which are not in stats yet
      all

  clipiqa_001:
    pretrained_netG: ../mnt/calypso/checkpoints/4x_finetune_vrt_vimeo_clipiqa_001/models/75000_G.pth
    metrics: # metrics which are not in stats yet
      all

datasets:   
  realhero:
    mode: FR
    name: fr_dataset
    name_zero_pad: 5
    save_results: True
    save_path: ../mnt/calypso/attacks/basicvsrpp
    save_stat_path: ../mnt/calypso/attacks/basicvsrpp
    dataroot_gt: ../mnt/calypso/datasets/realhero/realhero.lmdb
    dataroot_lq: ../mnt/calypso/datasets/realhero/realhero_lq_4x.lmdb
    cache_data: true
    io_backend: 
      type: lmdb
    num_frame: 7
    frames_interval_list: [0, 7]
    random_reverse: false
    use_hflip: false
    use_rot: false
    pad_sequence: false
    scale: 4
    dataloader_shuffle: false
    dataloader_num_workers: 12
    n_videos: all
  
  reds:
    mode: FR
    name: fr_dataset
    name_zero_pad: 8
    save_results: True
    save_path: ../mnt/calypso/attacks/basicvsrpp
    save_stat_path: ../mnt/calypso/attacks/basicvsrpp
    dataroot_gt: ../mnt/calypso/datasets/REDS/reds_val_gt.lmdb
    dataroot_lq: ../mnt/calypso/datasets/REDS/reds_val_lq_4x.lmdb
    cache_data: true
    io_backend: 
      type: lmdb
    num_frame: 7
    frames_interval_list: [0, 7]
    random_reverse: false
    use_hflip: false
    use_rot: false
    pad_sequence: false
    scale: 4
    dataloader_shuffle: false
    dataloader_num_workers: 12
    n_videos: all

  vimeo:
    mode: FR
    name: fr_dataset
    name_zero_pad: 0
    save_results: True
    save_path: ../mnt/calypso/attacks/basicvsrpp
    save_stat_path: ../mnt/calypso/attacks/basicvsrpp
    dataroot_gt: ../mnt/calypso/datasets/vimeo90k/vimeo90k_test_GT.lmdb
    dataroot_lq: ../mnt/calypso/datasets/vimeo90k/vimeo90k_test_LR7frames_4x.lmdb
    cache_data: true
    io_backend: 
      type: lmdb
    num_frame: 7
    frames_interval_list: [1, 8]
    random_reverse: false
    use_hflip: false
    use_rot: false
    pad_sequence: false
    scale: 4
    dataloader_shuffle: false
    dataloader_num_workers: 12
    n_videos: all
    